<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <Customer>
            <id>
                <xsl:value-of select="upper-case(/Customer/id)"/>
            </id>
            <fullName>
                <xsl:value-of select="/Customer/firstName,' ', /Customer/lastName"/>
            </fullName>
            <address>
                <line1>
                    <xsl:value-of select="/Customer/address/street,' ', /Customer/address/number,' ', /Customer/address/postcode"/>
                </line1>
                <line2>
                    <xsl:value-of select="/Customer/address/country,' ', /Customer/address/city"/>
                </line2>
            </address>
            <phone>
                <xsl:value-of select="/Customer/phone"/>
            </phone>
            <email>
                <xsl:value-of select="/Customer/email"/>
            </email>
            <accountType>
                <xsl:value-of select="/Customer/accountType"/>
            </accountType>
        </Customer>
    </xsl:template>
</xsl:stylesheet>